import type {
  CampaignId,
  CampaignInviteId,
  CampaignMemberId,
  CampaignName,
  CampaignRole,
  InviteTokenHash,
} from '@pioneer/campaign/domain';
import type { UserId, Version } from '@pioneer/shared/kernel';
import { sql } from 'drizzle-orm';
import { index, integer, pgTable, text, timestamp, uniqueIndex, uuid } from 'drizzle-orm/pg-core';

/**
 * Drizzle schema for the campaign aggregate. Migrations live in apps/api/migrations. Every lookup a
 * repository issues is served by an index here; the query-plan guard in the repository tests
 * enforces it. Foreign keys to users (on delete cascade) are in migration 0007, not here: identity's
 * tables are outside this context's module boundary.
 */
export const campaigns = pgTable(
  'campaigns',
  {
    // UUIDv4, generated by the application (newId()).
    id: uuid().$type<CampaignId>().primaryKey(),
    version: integer().$type<Version>().notNull(),
    name: text().$type<CampaignName>().notNull(),
    gmId: uuid().$type<UserId>().notNull(),
    // Strings, not Date: Date is banned; rows are converted to Temporal.Instant.
    createdAt: timestamp({ withTimezone: true, mode: 'string' }).notNull(),
  },
  // Serves the cascade when the GM's user is deleted.
  (table) => [index('campaigns_gm_id_idx').on(table.gmId)],
);

/**
 * One row per member of a campaign. The audit log keys rows by `id`, so a membership has its own
 * id; `(campaign_id, user_id)` is unique instead of being the primary key.
 */
export const campaignMembers = pgTable(
  'campaign_members',
  {
    id: uuid().$type<CampaignMemberId>().primaryKey(),
    campaignId: uuid()
      .$type<CampaignId>()
      .notNull()
      .references(() => campaigns.id, { onDelete: 'cascade' }),
    userId: uuid().$type<UserId>().notNull(),
    role: text().$type<CampaignRole>().notNull(),
    joinedAt: timestamp({ withTimezone: true, mode: 'string' }).notNull(),
  },
  (table) => [
    // A user is in a campaign once; also serves loading a campaign's members.
    uniqueIndex('campaign_members_campaign_user_idx').on(table.campaignId, table.userId),
    // At most one GM member per campaign; the service makes it the user in `campaigns.gm_id`.
    uniqueIndex('campaign_members_one_gm_idx')
      .on(table.campaignId)
      .where(sql`${table.role} = 'gm'`),
    // A member's campaign list, in the order they joined, campaign id breaking ties.
    index('campaign_members_user_joined_at_campaign_idx').on(table.userId, table.joinedAt, table.campaignId),
  ],
);

/**
 * Invite links. Only the token's SHA-256 is kept. The foreign key on `created_by` (to users, on
 * delete cascade) is in the migration, like the others to identity.
 */
export const campaignInvites = pgTable(
  'campaign_invites',
  {
    id: uuid().$type<CampaignInviteId>().primaryKey(),
    campaignId: uuid()
      .$type<CampaignId>()
      .notNull()
      .references(() => campaigns.id, { onDelete: 'cascade' }),
    tokenHash: text().$type<InviteTokenHash>().notNull(),
    createdBy: uuid().$type<UserId>().notNull(),
    createdAt: timestamp({ withTimezone: true, mode: 'string' }).notNull(),
    expiresAt: timestamp({ withTimezone: true, mode: 'string' }).notNull(),
    revokedAt: timestamp({ withTimezone: true, mode: 'string' }),
  },
  (table) => [
    // Joining looks a token up by its hash.
    uniqueIndex('campaign_invites_token_hash_idx').on(table.tokenHash),
    // The GM's list, newest first; also serves the cascade when a campaign is deleted.
    index('campaign_invites_campaign_created_at_idx').on(table.campaignId, table.createdAt, table.id),
    // Serves the cascade when the creating user is deleted.
    index('campaign_invites_created_by_idx').on(table.createdBy),
  ],
);
