import type { CharacterId, CharacterLevel, CharacterName } from '@pioneer/character/domain';
import type { AncestryId, AttributeModifiersWire } from '@pioneer/rules/sdk';
import type { UserId, Version } from '@pioneer/shared/kernel';
import { index, integer, jsonb, pgTable, smallint, text, timestamp, uuid } from 'drizzle-orm/pg-core';

/**
 * Drizzle schema for the character aggregate. Migrations live in
 * apps/api/migrations. Every sort or filter a repository issues must be served
 * by an index here; the query-plan guard in the repository tests enforces it.
 */
export const characters = pgTable(
  'characters',
  {
    // UUIDv4, generated by the application (newId()).
    id: uuid().$type<CharacterId>().primaryKey(),
    version: integer().$type<Version>().notNull(),
    // A user id. Its foreign key to users (on delete cascade) is in migration 0005, not here;
    // Identity's tables are outside this context's module boundary.
    ownerId: uuid().$type<UserId>().notNull(),
    name: text().$type<CharacterName>().notNull(),
    // Content id (UUIDv5 of `<pack>/<slug>`); every id column is a uuid.
    ancestry: uuid().$type<AncestryId>().notNull(),
    level: smallint().$type<CharacterLevel>().notNull(),
    attributes: jsonb().$type<AttributeModifiersWire>().notNull(),
    // Strings, not Date: Date is banned; rows are converted to Temporal.Instant.
    createdAt: timestamp({ withTimezone: true, mode: 'string' }).notNull(),
    updatedAt: timestamp({ withTimezone: true, mode: 'string' }).notNull(),
  },
  (table) => [
    // One index per CharacterSort option within an owner's characters, with id as the tie-breaker
    // The list query orders by. Asc and desc both use it (backward index scan).
    index('characters_owner_created_at_id_idx').on(table.ownerId, table.createdAt, table.id),
    index('characters_owner_name_id_idx').on(table.ownerId, table.name, table.id),
  ],
);
