import type { AttributeModifiersWire } from '@pioneer/rules/sdk';
import { index, integer, jsonb, pgTable, smallint, text, timestamp, uuid } from 'drizzle-orm/pg-core';

/**
 * Drizzle schema for the character aggregate. Migrations live in
 * apps/api/migrations. Every sort or filter a repository issues must be served
 * by an index here; the query-plan guard in the repository tests enforces it.
 */
export const characters = pgTable(
  'characters',
  {
    // UUIDv4, generated by the application (newId()).
    id: uuid().primaryKey(),
    version: integer().notNull(),
    name: text().notNull(),
    // Content id (UUIDv5 of `<pack>/<slug>`); every id column is a uuid.
    ancestry: uuid().notNull(),
    level: smallint().notNull(),
    attributes: jsonb().$type<AttributeModifiersWire>().notNull(),
    // Strings, not Date: Date is banned; rows are converted to Temporal.Instant.
    createdAt: timestamp({ withTimezone: true, mode: 'string' }).notNull(),
    updatedAt: timestamp({ withTimezone: true, mode: 'string' }).notNull(),
  },
  (table) => [
    // One index per CharacterSort option, with id as the tie-breaker the list
    // Query orders by. Asc and desc both use it (backward index scan).
    index('characters_created_at_id_idx').on(table.createdAt, table.id),
    index('characters_name_id_idx').on(table.name, table.id),
  ],
);
